sherlock-project/sherlock

- data.json
There were two entries for https://houzz.com/user. Must have been a cut-and-paste error.
> Remove duplicate for Houzz

- sherlock.py
On my Windows machine, json.load(raw) raises error due to the default encoding chosen by open(). I believe this affects other machines that does not use utf-8 as default. We can get around this problem by enforcing 'utf-8' when we open data.json.
> enforce utf-8 encoding when we open data.json

- sherlock.py
HTTP requests error handling
Also adding command line parameters
> Error handling

- sherlock.py
Fix bug that incorrectly said that all user names were not supported for any site that would not allow a dot in the user name.
The check for the dot should only happen if the user has a dot in the name.
> Correct User Name With Dot Check

- data.json
- sherlock.py
Replace noPeriod attribute in JSON file with a regexCheck attribute.  If this does not exist in the JSON file, then there will be a default regular expression that will be used.  By default, the allowed user name pattern requires that the first character is alphabetic, while the following characters are either alphanumeric or ".", "_", or "-".  Also, specifically indicate that the user name is invalid in the feedback.
> Allow Site-Specific Username Checking By Regular Expression

- sherlock.py
Removed default regular expression check, only check when regular expression is specified in the settings file.
In the old code, a default regular expression ("^[a-zA-Z][a-zA-Z0-9._-]*$") was set to check the username against if no regex for the specific website was set in the settings file. When no regex for the specific website is set, however, it is impossible to determine whether a username is actually invalid even if it does not match the default regex. 
A nice example is flickr.com: a user with as username "00" exists on the website ([link](https://www.flickr.com/people/00)), but would not match the default regular expression and would thus never be checked. This actually goes for all usernames starting with a number. Altering the default regular expression could of course eliminate …
> Altered regex_check logic

- .gitignore
- sherlock.py
Change sherlock method to return dictionary summarizing all results. This will allow the caller to have raw information for other reports.
This is for #32.
> Add CSV Report For Results

- .gitignore
- sherlock.py
A HEAD request do not download the body as the GET request does which minimizes the overhead a tiny bit.
> If only status_code is needed use HEAD instead of GET request 

- data.json
- sherlock.py
"os.path.isfile(fname)" is case-insensitive while "os.remove(fname)" is case sensitive, this means that if you search a username, and then search it again with a different case, there will be a FileNotFoundError.
> Fix case sensitivity bug

- install_packages.sh
The script downloads the packages that are necessary for the sherlock.py. It is an automated procedure instead of the instructions in the README.md.
It contains some packages that are not in README but I couldn't run "pip3 install -r requirements.txt" without them.
It is for linux, I don't know if it works on something else.
I believe it is useful!
Sorry for the extra files from previous pull request (if they are shown), but I'm new on Github and I' confused with commits and forks.
> Script for installing packages in linux

- data.json
Facebook from: https://www.facebook.com/help/409473442437047 but I don't know how to handle this requirement: "They can't contain generic terms or extensions (.com, .net)".
Flipboard from: https://flipboard.helpshift.com/a/flipboard/?s=managing-your-account&f=help-with-username-issues&p=web
> Add "regexCheck" for Facebook and Flipboard

- sherlock.py
When username argument was provided with uppercase chars, sherlock
said that file was saved into "UserName.txt" instead of "username.txt" (fname var)
> Fix incorrect file save notification

- README.md
Their was an </a> in README.md but no starting <a> anchor.
> Remove useless end of <a> anchor in README.md

- README.md
- sherlock.py
Add command line option to only run a report on specified sites (as opposed to all of them).  Move loading of JSON file out of the query logic proper: we need to keep the database and the query logic separate anyway for future changes, so this is a first step in the refactoring.  Update readme file with latest information.
This is one installment on #37.
> Command Line Option To Specify Sub-Set Of Sites To Query

- README.md
- sherlock.py
Fixes #82 
- Exposes metrics about each request's response time (in milliseconds)
- In verbose mode, prints out response times to console
Please note that long "response times" are not entirely the fault of the websites we make requests to. These response times are **highly influenced** by a variety of factors on your computer, such as Context Switching. All requests run in separate threads, but access to the network card for I/O is blocked to one request at a time. Therefore, some responses might be "done" earlier than your CPU can process them.
This needs to be tested and understood further (I plan on doing that later). So this PR only exposes these metrics, but doesn't take any actions on them or imply that long response times correlated to the website.
I was able to make use of …
> Response time metrics

- data.json
The main problem with VirusTotal false positives was redirection, so the response code was not handled correctly. My solution fixes this, but the main problem now is that the URL of the user account is actually an API request with a JSON response. It consists of the URL of the home page of the user account, so I do not know whether it is a real problem to find out.
A JSON response if the user exists:
```
{
"data": [],
"links": {
"self": "https://www.virustotal.com/ui/users/root/trusted_users?limit=10"
}
}
```
A JSON response if the user doesn't exist:
```
{
"error": {
"code": "NotFoundError",
"message": "User \"tdh8316\" not found"
}
}
```
HEAD requests to this url permitted, thus it parses `error` from small JSON response page.
> Fixed #99: VirusTotal false positive.

- sherlock.py
While running tests, I was getting a ResourceWarning about an unclosed file. The result file was not being closed, so it was a valid warning.  Close the file to avoid this warning.
> Explicitly Close Result Text File

- data.json
- sherlock.py
- tests/all.py
This is to resolve #128. Note that all of the sites effected by this bug are devRant/iMGSRC.RU/ImageShack/MeetMe.  The other sites using the Response URL detection strategy worked before.
Previously, there was a problem with sites that redirect an attempt to view a non-existing username to the main site. For example, if you try to go to https://devrant.com/users/dfoxxxxxxxxx (a user name that does not exist), then we get a redirect to the https://devrant.com/ root of the site. But, the "response_url" checking algorithm was only looking for the configured error URL being included in the response.  So, these sites always indicated that the username was not found.
Update the "response_url" detection method so that the request does not allow redirects. If we get a 200 response of some type, …
> Response URL Site Detection Strategy Overhaul

- README.md
All of the other commands start with $, so it is better to be consistant.
> replaced % with $ in README.md

- site_list.py
In `site_list.py`, `url_main` is present in the tuple appended to `pool` twice - `(url_main, url_main, th)` which would yield incorrect results. It should be `(social_network, url_main, th)`.
> Fix issue with site name and url

- README.md
- data.json
- sherlock.py
- tests/all.py
- tests/base.py
Yet another installment in #37.
We really need to get the process such that the individuals that add sites to the JSON file also update the tests.  So, there is now information about a claimed and an unclaimed username in the site information. This will allow the tests to directly source the information from the JSON data.  It will also allow people who add new sites to also add test data (which will automatically get tested).  Add a new test method which finds all sites of a given detect algorithm, and which also has test vectors, and runs tests against them.
At the current time, the test vectors are optional.  But, once when there is finally complete coverage, then they will be required.  Anyone who adds a site without also adding test data will trigger a failure.
> JSON Driven Tests

- data.json
Another iteration on #37.  
Added more sites to JSON driven tests.
Fix tests for BuzzFeed and Canva.  Someone has claimed the user name "noonewouldeverusethis7" on both of these sites.  The irony is not lost on me.
I don't get how the name was chosen.  I doubt that it was coincidence. Is there some monitoring of queries to the sites, and someone is claiming them?  Or, is someone in the Sherlock community just being a pain?  In any case, this does not bode well for having a repeatable test.
> Yet Even More Tests

- README.md
- data.json
- sherlock.py
Fix false positive for 500px. The site changed their error text, so Sherlock started reporting false positives.
> Fix False Positive On 500px

- sherlock.py
This approach is a bit strange to read the first few time but has advantages in that it is easier to get right and faster to execute.
The interactions between `and`, `or`, `not`, and `()` can get confusing for new coders.  For example, just a few lines above this PR's changes the code line 308 does not match the comment on 307 and I believe that in this case the comment correct and the code is wrong (for values < 200) because it is missing parens.  I believe that __200 <= status_code < 300__ produces the correct results in a readable (semi-)intuitive code.
```
>>> for status_code in (-1, 1, 199, 200, 201, 299, 300, 301, 1000):
...     print(not status_code >= 300 or status_code < 200,
...           not (status_code >= 300 or status_code < 200),
...           200 <= status_code < 300)
... …
```
> Use compound if statement rather than "if and"

- README.md
I think putting original creator under License will be a much better place. Or at least right above `License`. What do you guys think? @sdushantha @TheYahya 
Totally just an option.
> Put the original creator to license section.

- Dockerfile
- README.md
Heya, 
To link the of the image published on Docker Hub with the git revision I've introduced some labels in the image. This should help identifying  mismatches between container and repository versions faster like in the case of #175.
- Added build-args that will be transformed into labels
- Added a badge to the readme where you can [view details of the latest docker image](https://microbadger.com/images/theyahya/sherlock).
- Build image with `docker build -t mysherlock-image . --build-arg VCS_REF=$(git rev-parse HEAD)`
- Acknowledge that `docker image inspect mysherlock-image` will show the labels
- Build the image without the build-arg, notice that it does not break the build.
Let me know if you want anything changed. Thank you for the awesome project 😄
> Label the Docker image with some VCS repository information

- data.json
Heya,
This PR should add Docker Hub to the searchable websites. Using the hints you provided with a separate `urlProbe`. 
1. Checkout PR branch
1. Run `python3 sherlock.py nstapelbroek --site Docker\ Hub`
1. Acknowledge result
Thanks!
> Add hub.docker.com

- README.md
- data.json
- sherlock.py
- sites.md
Convert Flipboard to use more reliable HTTP Status detection method.  The site gives a clean 404 error.  They changed their site response, so we were getting false positives.
Wikia has been renamed to Fandom.  The old http://www.wikia.com/ site redirects to https://www.fandom.com/, so the detection was not working.
Convert Reddit to use more reliable HTTP Status detection method.  The site gives a clean 404 error.
> Fix Broken Sites

- data.json
Added support for:
- [Discogs](https://www.discogs.com/)
- [Rate Your Music](https://rateyourmusic.com/)
I ran `site_list.py` but that replaced all ranks with zero. Testing the Alexa API in a browser simply returned `Okay` for some reason.
> Add Discogs and RYM

- data.json
username_claimed 'blue' for BitBucket no longer works.
Accordingly, I replaced `blue` with `white`.
> Update claimed username for BitBucket.

- .travis.yml
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__python/black__](https://github.com/python/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where …
> Travis CI: Add more flake8 tests

- data.json
Hello,
This is for Issue #223
Wattpad returns HTML message for non-existent users. In that message, the "userError-404" div tag id is used to render the 'User Not found' message. 
So, I am using this tag id to check whether the user not exist and preventing the false positive issue. 
Thanks and Regards,
Sathish K
> ISSUE-223 Wattpad site false positive issue

- data.json
Currently, the system is not working for Pinterest because the site will always return a status code of 301 no matter the username exists or not.
I changed it to use status_code. Pinterest will eventually return a status code of 404 if the username does not exist.
> Fix Pinterest

- .travis.yml
- tests/all.py
This update is in regards to the discussion in #235 .  
There are so many sites that are unreliable, it is pretty uncommon for the tests to run without one or the other failing to respond and causing the tests to fail.  So, this update changes the CI tests to only run against a subset of sites.  These are more popular sites that should be less likely to go down.  The tests will exercise Sherlock so that it will try each of the detection methods.
Part 2 will be to devise a CI test that does the site coverage.
> Robustness Update For CI Tests (Part 1)

- sherlock.py
This problem happens during the write to the CSV.  There are various results that are gathered during the query for the existence of a given site, and they are always expected to exist in the results dictionary.  However, if a given user name has an illegal format for a given site, then the query is not even attempted.  Which leaves some keys in the dictionary undefined.
The solution is to define these keys even in the case where the username has an illegal format.
See #252
> Fix Error When csv Is Written When Username Is Illegal For A Site

- data.json
It appears that they have changed their website. Before, they rendered their "Page Not Found" error message in HTML. Now, they must be creating that text with javascript.
Lucky, they do have an unauthenticated API available.  So, change the detection to use that.
See #258
> Fix MixCloud false positive.

- README.md
I have added a link to the README.md that will allow anyone to test Sherlock directly in the browser.
Just try it out and you will see what I mean: [https://elody.com/scenario/plan/16/](url)
Is this useful for you?
I am building a website that can let anyone make their code available to endusers without download or installation.
I used Sherlock as a test case, because it was recently trending on github and it seemed like a good fit.
My goal is that developers will upload their existing github projects to elody.com and put the link to it on their github page, to make showcasing the projects more convenient. Elody can also do a whole lot more than that, but it's a good way to get started.
Do you like it?
Is there anything else you would like to see to make this more useful?
I would really …
> Adds a link to let github visitors test Sherlock from their browser

- data.json
Please note: Google PlayStore dev ids are case-sensitive. So for example, If `Facebook` is registered and you search for `facebook`, then it'll return `404`.
There is no way out as of now.
> Add PlayStore

- data.json
Addition: NPM Package names are unique and they're sometimes reserved by the devs as many have lost the good names to others because of neglecting and end up having different package names pointing to different GitHub repos (which is often confusing but no choice).
Change with NPM is simply because the status code algo just works fine and no need to rely on an unstable algo (message) and the head request would just be sufficient as well.
> Add NPM Package & Change NPM to Status Code

- data.json
Status code algo for some reason isn't working with Sherlock for this site (but works if I do a cURL request or from any other tool). So I had to go with message algo which does the job but I'd prefer status code if possible.
> Add Trello

- data.json
Corrected and relaxed regex for Facebook, now accepts
* cnn
* bbc
* id.co
* MINI.uk
* lifo.mag
* lukonet
#262
> Facebook regex fix

- data.json
* Canva
* `blue` is no longer taken, replaced with `jenny`
* Flightradar24
* `noonewouldeverusethis7` is taken, replaced with `xgtrq`
* Twitch
* `blue` is no longer taken, replaced with `jenny`
> Changed taken usernames

- README.md
- data.json
- sherlock.py
Convert Trip to use more reliable HTTP Status detection method.  The site gives a clean 410 error.  They changed their site response, so we were getting false positives.
This has been noticed in issues #325 and #326.
> Fix Trip False Positive

- data.json
Good morning 👋 
Chances are that you are running this software on a desktop environment rather than a mobile so I took the liberty of splitting the twitch result url from the probe url.
The result: Users found on twitch will now be linked using `www.twitch.tv/username `instead of `m.twitch.tv/username`. 
Let me know if you have any feedback 😄
> Use browser URL for twitch.tv results

- sherlock.py
I've added support for custom headers in the `data.json` file for each site. If no headers are declared, which is the case for all current sites, it will use the same User-Agent in the header as before. To declare custom headers  add a dictionary to a site in `data.json` called "headers" as demonstrated below.
```
"Zomato": {
"errorType": "status_code",
"url": "https://www.zomato.com/{}/foodjourney",
"urlMain": "https://www.zomato.com/",
"username_claimed": "deepigoyal",
"username_unclaimed": "noonewouldeverusethis7",
"headers": {
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0",
"Origin": "https://www.zomato.com/"
}
```
This was made in response to #256.
> Added support for custom headers

- README.md
When I used Anaconda on Windows, using 'python3' did not work. Only 'python' worked in those cases. My change will be useful for Windows users.
> Added notes for Anaconda users

- .gitignore
- requirements.txt
This intend to fix the _RuntimeError: dictionary keys changed during iteration_ which happens on `stem` package by using the specific commit where the bug was fixed.
Since there is no new release from `stem` since that bugfix, the only solution is to patch de dependency code or install from git (my choice).
Details in the following links:
- https://www.mail-archive.com/tor-bugs@lists.torproject.org/msg186952.html 
- https://gitweb.torproject.org/stem.git/commit/?id=b5aecb7
> Fix / Install stem requirement from git

- .gitignore
- README.md
- data.json
- sherlock.py
- tests/base.py
Some websites may fail to respond to the requests at all, as a result the process will be stuck, a simple solution is to set a timeout, as supported by the `requests` module.
- Add a fixed timeout to all requests (currently set to 10s)
Note: In my tests, 10s was enough even with Tor. Sometimes a site may take longer to respond, but a longer timeout will make the script takes to much time (waiting + retries) and the retries will usually handle intermittent connections.
- Change Flipboard unclaimed username
- Add a `tests/.excluded_sites` list to allow pass tests for unresponsive sites
This PR shall fix these issues. 
It would be nice if the reporters could check if they still persist.
- https://github.com/sherlock-project/sherlock/issues/323 (@MinePro120)
- …
> Fix / Add a timeout to avoid hanging requests

- requirements.txt
This should the issues some people have been having with installing the `stem` module.
fixes #496
> Use stem from PyPi insted of Git version, fixes #496 

- data.json
Adds some popular mastodon instances (chaos.social, mastodon.social, mastodon.xyz, pawoo.net, social.tchncs.de) and changes the existing 'Mastodon' instance to its own name 'mstdn.io", because mstdn.io is not the whole mastodon fediverse. Also adds imageboard pr0gramm.com
> adds Mastodon instances and pr0gramm.com

- data.json
CreativeMarket changed their user URL from `https://creativemarket.com/blue` to `https://creativemarket.com/users/blue`.
> Update CreativeMarket to their new url

- data.json
- site_list.py
removed unused variables. 
updated data.json and tested it. 
worked.
> Added soylentnews

- README.md
- sherlock/resources/data.json
- sherlock/sherlock.py
This is a restructuring of #593.
Add override to HTTP Status Detection so HEAD request is not used.  Configure Instagram to use this option.
In most cases when we are detecting by status code, it is not necessary to get the entire body:  we can detect fine with just the HEAD response.  However, Richard Getz discovered that some sites (e.g. Instagram) will not respond properly if Sherlock only requests the HEAD.
Add a "request_head_only" attribute to the data.json so HTTP Status Detection can be configured either way.  It is simpler to support this change in this fashion, as it does not require changes to the tests.
With Richard Getz <richardgetziii@gmail.com>
> Support HTTP Status Detection GET Override.  Use For Instagram

- sherlock/sherlock.py
- sherlock/sites.py
- sherlock/tests/base.py
I used the "importchecker" pip plugin for this
```
pip install importchecker
importchecker .
```
Keeping unittest since that seems important.
Note: I ran unit tests, and 5 things failed, but they seemed to be failing before (and all assertion errors, nothing from a missing import)
> Clean out unused imports

- sherlock/notify.py
- sherlock/sherlock.py
- sherlock/sites.py
This is not a significant change. But the [documentation](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) said that comparisons to singletons like `None` should always be done with `is` or `is not`, never the equality operators.
> Use `is` operator when comparing singletons.

- removed_sites.md
- sherlock/resources/data.json
Like mentioned in #647 forum.redsun.tf seems to be giving false positives. In this PR, this site will be removed because of the way the site uses usernames, Sherlock is not able to check the usernames.
> removed forum.redsun.tf

- .dockerignore
After diving into the current image I noticed that the `venv` was copied in there. This PR should prevent that from happing in future builds.
- added venv folder to the .dockerignore
- I also noticed that the current image on docker hub has a layer for `RUN /sbin/apk add tor`. Is this supposed to be there? Maybe we can rebuild the image to reflect the Dockerfile in the repository.
> Prevent copying of venv folder in the Docker image

- sherlock/resources/data.json
I found out that when a username that does not exist is used, we get redirected to `https://ko-fi.com/art?=redirect`
> fixed false positive for Ko-fi

- sherlock/__main__.py
This will hopefully prevent people from opening issues where the problem is that the user
is using a version of Python which is lower than 3.6. Sherlock only supports 3.6+
This hack was taken from h8mail created by @khast3x
Source: https://github.com/khast3x/h8mail/blob/master/h8mail/__main__.py
> Check Python version before executing the main function of Sherlock

- sherlock/resources/data.json
An online forum-like community targeted towards Nigerians.
- Alexa rank: 808
- 6th site in Nigeria
- nearly 2.5mln user accounts
- exists since 2005
Sources:
https://www.alexa.com/siteinfo/nairaland.com
https://en.wikipedia.org/wiki/Nairaland
> add nairaland.com

- data_bad_site.json
- removed_sites.md
- sherlock/resources/data.json
The Incorrect URL for Angel List has been updated.
However, it is still not possible to verify usernames in this site as the request generates a Forbidden 403 Error.
Edit:
Telegram Username check is modified and works now.
Changed Error type from status_code to errorMsg.
Thus, removed entry from removed_sites.md
> Telegram Works Now | Updated the correct URL for Angel List

- data_bad_site.json
- removed_sites.md
- sherlock/resources/data.json
CapFriendly returns Fake Profiles that seem indistinguishable.
Found a cheeky difference that appeared in Faked Profiles but did not in Actual Profiles.
`<div class="err show p5">No results found</div>`
Matching Error Message against this tells us if the user exists or not.
> Fixed CapFriendly Check

- data_bad_site.json
- removed_sites.md
- sherlock/resources/data.json
9Gag was marked as reporting all usernames as valid.
Going through today (06.08.2020) I found that the site returned different pages when called as:
> https://9gag.com/ 
-- Returned a 403 Error on POSTMAN with some HTML on Cloudfare Error.
and
> https://www.9gag.com/
-- Returned the correct HTML page.
Weird and I am not sure why.
But testing usernames after adding www, it works magically!
> 9Gag Works! Weird.

- sherlock/sherlock.py
If the there is a newer version available on GitHub then the user will
be told. This to encourage users to have the up to date version of
Sherlock which has the newest features.
> added version checking

- sherlock/resources/data.json
Metacritic does not allow . in its username which was the one causing issues with Sherlock.
> MetaCritic Regex & False Positive Fix

- sherlock/resources/data.json
eBay uses the same title for non-existent profiles irrespective of the language, which we now use as ErrorMsg.
> Fixed eBay False Positive on Other Languages

- sherlock/sherlock.py
Hello
I found a small bug:
```
site_data = {}
site_missing = []
for site in args.site_list:
for existing_site in site_data_all:
if site.lower() == existing_site.lower():
site_data[existing_site] = site_data_all[existing_site]
if not site_data:
site_missing.append(f"'{site}'")
f site_missing:
print(
f"Error: Desired sites not found: {', '.join(site_missing)}.")
sys.exit(1)
```
If user inserts multiple sites with ```--site```, and program correctly finds one of the sites, the next ones won't be added to ```site_missing``` even if they are wrong. For example ```python sherlock username --site facebook --site twittter```
won't print out message about wrong twittter site name, because site_data has item (facebook). I solved it with counter variable instead of checking ```if not site_data:```. …
> fixed missing_sites

- sherlock/resources/data.json
As mentioned in #725, Sherlock could not find usernames based on a facebook privacy setting.
This fixes that by using a different URL to check -> https://www.facebook.com/{}/videos/ which would say "You must log in to continue" if such a profile existed, else would give us a "This page isn't available".
> Facebook False Positive Fix

- sherlock/sherlock.py
Having to use ```--json sherlock/resources/data.json``` to use the local data.json seems a bit cumbersome, so I've added a simple "--local" or "-l" argument to force it's use.
> Added --local argument for local data.json use

- sherlock/notify.py
- sherlock/sherlock.py
This flag will output all the sites regardless the QueryStatus.
As mentioned by @hoadlck, this flag is more appropriate than using
--verbose, which is the flag I set to serve the same purpose as
--print-all in the previous commit. More of the discussion about this
flag can been viewed in #747
> added a --print-all flag

- README.md
- sherlock/sherlock.py
Restore --print-found option.
Now --print-all and --print-found complement each other.  The default remains that only the found are reported.
Update documentation on timeout command line option.
> Update Command Line Options

- sherlock/resources/data.json
Quirky.
In places CashMe operates, Usernames that do not exist give,
```javascript
{
"success": false,
"message": {
"message": "",
"already_localized": true
},
"debug_info": ""
}
```
In places CashMe does not operate, we get the following,
```html
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Cash App</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
<link rel="stylesheet" type="text/css"
...
```
*ss"* is a match on the Non-Existing Usernames in places CashMe operates through the standard JSON response and also on countries that do not have CashMe through the standard HTML response. 
This cannot be found on the HTML response for Existing Usernames in places CashMe operate.
> CashMe Fix

- sherlock/resources/data.json
Usernames with dots led to false positives for freelance.habr. Changes in this PR add a regex check to prevent the issue from occurring.
> Fixed false positive for freelance.habr

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/reporting-false-negative.md
- .github/ISSUE_TEMPLATE/reporting-false-positive.md
- .github/ISSUE_TEMPLATE/site-support-request.md
- CONTRIBUTING.md
- removed_sites.json
- removed_sites.md
- sherlock/__main__.py
- sherlock/resources/data.json
- sherlock/sherlock.py
As of now, Sherlock supports only a single instance for error messages. I have added the functionality which can handle the list/array of error messages.
Taking an example of Tinder, it provides multiple kinds of error. So, I have added those error messages in the data.json file.
Now the core module sherlock.py only supports one error message in form of string. So I have modified that file and handled the case so that it can support a list/array of messages.
As a result, Tinder which was reporting False-Positives is handled, and now it returns correct results.
Also, this can be helpful in the future, in order to support multiple error messages for different sites.
> Adding facility to support multiple errors

- sherlock/resources/data.json
Use `errorMsg` instead of `errorUrl` as it is more reliable.
> use errorMsg for Quora

- sherlock/resources/data.json
NOTE: This is not the same thing as GitHub, as not all Github users have a Github Support Community account.
> Add support for GitHub Support Communities

- sherlock/resources/data.json
This PR fixes the false positive for Onlyfans by using their API to check for the existence of a user.
> Fixed false positive for only fans

- sherlock/resources/data.json
Switch RuneScape over to the API endpoint instead of the web app to avoid issues with false positives.
More information:
* https://github.com/sherlock-project/sherlock/issues/1189
> fix runescape detection

- sherlock/resources/data.json
babyblogRU changed how their URLs are formatted, they've also made users not-found redirect to the homepage instead.
More information:
* https://github.com/sherlock-project/sherlock/issues/1189
> fix detection for babyblogru

- sherlock/resources/data.json
Sorry, quite a few of these are my fault. I just realized when I ran the tests, it wasn't using my local copy of `data.json`? 🤔 I feel like this one is me being stupid. 
I only just noticed now too, when I do `python3 sherlock {username} --site RuneScape` for example, it doesn't use my local copy unless I specify it with `-json sherlock/resources/data.json` manually. 🤔 Is that intended, or am I being stupid here too?
| Site(s) | Change
|---|---
| GNOME VCS | Forgot to escape the dot at the end of the regex.
| HEXRPG, Nextcloud Forum, WICG Forum | I'm dumb and put an impossible username as the unclaimed test.
| Tenor, Nightbot | Someone accidentally put an impossible username as the unclaimed test.
> fix username_unclaimed fields with invalid usernames

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
- sites.md
Removed TM-Ladder due to rate limits, more information here:
* https://github.com/sherlock-project/sherlock/issues/1189
While I was at it, I renamed `TrackmaniaLadder` to `TM-Ladder` which is how it's referred to on its website. (The TM does stand for TrackMania, however understandbly, it doesn't use the TrackMania trademark in the website name.)
> Remove TM-Ladder (TrackmaniaLadder)

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
- sites.md
* Fix ICQ by moving it to `status_code`. I also added a locale to the URL to avoid the redirect (30x).
* Removed plug.dj as the website is down for now, they are hoping to return at some point.
* Added Coil and Anilist to `removed_sites.json` as I forgot to do this before. _whoops_
I'm not sure why Git thinks I changed every line of removed_sites.json, might be encoding related? But looks like the encoding was `us-ascii` before and after this change according to `file -bi removed_sites.json` anyway.
> Fix ICQ and Remove plug.dj

- .editorconfig
Proposal to add 2 new properties to `.editorconfig`.
Both are [Ideas for Domain-Specific Properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#ideas-for-domain-specific-properties), so not all implementations support them, but some do, especially `quote_type`.
Even for editors that don't support them, it's a nice way to document the project's conventions. For example, the use of `"` and `'` is very inconsistent in the project. I'd like to confirm what convention is preferred and clean that up, as well as apply it for future code contributions.
It looks like double quotes are used more, so I set it to `double` for now. Let me know if it should be `single`.
> chore: add spaces_around_operators and quote_type

- .github/ISSUE_TEMPLATE/question.md
- README.md
- sherlock/sherlock.py
* StackOverflow → Stack Overflow (it has a space in it!)
> — https://stackoverflow.com/
* Replaces the microbadger badge with a Docker version badge from Shields.IO.
> — https://github.com/microscaling/microbadger
> — https://twitter.com/microscaling/status/1361054926399557644
> Fix typo and replace dead link

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
- sherlock/sherlock.py
- sites.md
Adds support for Anilist by allowing POST requests. Note, I don't do Python much, so just let me know if the code is crap. ^-^'
This is just a first iteration, it should already work without breaking any existing functionality. You're welcome to give feedback though if you feel I'd done something wrong.
* Adds Anilist back in to `data.json`. (For testing the implementation of this PR.)
* Adds an `interpolate_string` function, because I thought it would be nicer if we could define the `request_payload` as JSON rather than as a string literal. Opinion welcome!
* Allow `data.json` to specify the request method, defaulting to `HEAD`/`GET` based on the `errorType` if not specified.
* Replaces the now redundant `"request_head_only": false` with `"request_method": "GET"`
This replaces the use of …
> feat: support post requests

- sherlock/sherlock.py
- sherlock/tests/all.py
- sherlock/tests/base.py
- site_list.py
This is a follow-up to https://github.com/sherlock-project/sherlock/pull/1208.
Change all single quoted strings to double quotes, except where one is used inside the other.
This is just to make the repo more consistent.
> chore: make quotes in repo consistent

- README.md
> Remove broken cloud shell links from readme

- sherlock/resources/data.json
Adds the `regexCheck` property to Twitter.
Updates `username_unclaimed` to match regex.
Regex based on rules in the documentation:
https://help.twitter.com/en/managing-your-account/twitter-username-rules
After making the initial PR, I noticed a similar PR which added a regex check but allowed shorter usernames. #1049
After manually testing, it seems new Twitter accounts must be between 4 and 15 characters, but there are many existing Twitter accounts with 1-3 characters as well.
* Closes https://github.com/sherlock-project/sherlock/issues/1034 - Already solved, but raised an issue regarding usernames which is addressed here.
* Closes https://github.com/sherlock-project/sherlock/pull/1049 - Made redundant since we don't need to remove Twitter, plus detection has changed a lot since then.
* …
> twitter: add regexcheck for username

- sherlock/resources/data.json
- sherlock/sherlock.py
**`errorCode`** can be assigned in the data file.
If the target URL returns the given `status code`. It will result in an `AVAILABLE` username.
Added code for checking if the user is a valid Minecraft account
> Improving status code & added Mojang/Minecraft

- sherlock/notify.py
- sherlock/sherlock.py
This PR improves the handling of the no-color flag by enabling/disabling color output with the colorama.init() function, thus making the if statements to check for color output redundant. Therefore, the code is more concise and clean.
> Refactoring of the no-color flag

- sherlock/sherlock.py
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace all `git.io` links with their actual URL.
> Replace all `git.io` links

- sherlock/resources/data.json
* The regex was written poorly, I thought `{,12}` could be written instead of `{1,12}` but apparently not.
* At the time I added this, I didn't understand the difference between `url` and `urlProbe`. This actually takes the user to the profile rather than the API now.
* Replaced the `claimed_username` with an actual public profile.
> fix: fix false-negatives runescape

- sherlock/resources/data.json
Fix failing GitHub Actions
Given that the test engine reads MASTER only, these changes will not take effect until **after** this PR is merged into MASTER.
As discussed at https://github.com/sherlock-project/sherlock/issues/165#issuecomment-1177399092 the unclaimed username should be calculated, not read from a static file.
> data.json: Reset Pinterest unclaimed & VK claimed

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
The problem with the previous way (https://github.com/sherlock-project/sherlock/commit/d7402b89c6bed24ea0975252f718961fb963db83) was only the `errorType` of the request.
On a failed request, the return code from snapchat will be **404**, on a successful one it will be **200**. I changed it from `message` to `status_code` and removed the unnecessary parameters.
Also removed Snapchat from the list of the removed sites.
> Fixed the support for snapchat

- sherlock/sherlock.py
Added a function to exit gracefully.
**Before**
```console
$ python3 sherlock sdushantha --print-all
[*] Checking username sdushantha on:
[-] ResearchGate: Illegal Username Format For This Site!
[-] 2Dimensions: Not Found!
[-] 3dnews: Not Found!
^CTraceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/mnt/c/Users/siddh/Projects/sherlock/sherlock/__main__.py", line 22, in <module>
sherlock.main()
File "/mnt/c/Users/siddh/Projects/sherlock/sherlock/sherlock.py", line 665, in main
results = sherlock(username,
File "/mnt/c/Users/siddh/Projects/sherlock/sherlock/sherlock.py", line 355, in sherlock
r, error_text, …
```
> Added a function to exit gracefully.

- sherlock/notify.py
This PR fix a typo on documentation of countResults function
> docs: fix a typo on function documentation

- CONTRIBUTING.md
I have removed the section from CONTRIBUTING.md which says users may not submit adult sites to the site list, as several have already been included in sites.md.
`This PR is part of my Hacktoberfest contribution.`
> Remove Section Regarding Adult Sites from CONTRIBUTING.md

- sherlock/resources/data.json
Fix #1509
```
sherlock.py --local --site G2G jason-mayes 
[*] Checking username jason-mayes on:
[*] Results: 0
[!] End:  The processing has been finished.
Process finished with exit code 0
```
> add regex for g2g username

- sherlock/resources/data.json
Add in BiggerPockets.com forum -  a popular real estate forum
Examples:
Claimed: https://www.biggerpockets.com/users/blue - returns a status code of 200
Unclaimed: https://www.biggerpockets.com/users/noonewouldeverusethis7 - returns a status code of 404
> Add BiggerPockets.com

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
There was a missing letter in the url to look for the username, after that a cookie was needed to bypass the google agreements.
> fix: add Youtube to work again

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
- sites.md
The website was shut down in October and has no DNS records.
https://ashfurrow.com/blog/mastodon-technology-shutdown/
Signed-off-by: r3g_5z <june@girlboss.ceo>
> Remove mastodon.technology

- .github/workflows/main.yml
- .github/workflows/nightly.yml
This should fix the new issue that occurred yesterday where the workflows were failing
> dropped python 3.6 for worflows

- sherlock/resources/data.json
Added support for https://codeforces.com/ that was removed in the past after discussion in #1654.
Please let me know if any additional information/changes are required.
> Add support for removed site Codeforces

- sherlock/resources/data.json
Added support for https://monkeytype.com/.
[Monkeytype](https://monkeytype.com/) is a famous website for typing tests to improve typing skills, competing in leaderboards, etc. with a clean minimalistic interface.
Please let me know if any additional information/changes are required.
> Add support for Monkeytype

- sherlock/sites.py
A very small detail here !
Not sure if it was intentional or not, but I found that the docstring for the parameter `is_nsfw` is missing !
> [doc] Added missing parameter in docstring

- sherlock/resources/data.json
Amino already exists as "Amino", the existence of this one causes Amino accounts to be displayed twice.
> Remove duplicate Amino

- requirements.txt
- sherlock/resources/data.json
- sherlock/sherlock.py
- sherlock/tests/all.py
- sherlock/tests/base.py
1. Generate unclaimed username based on regex with `exrex`. The regex couldn't be fetched from `data.json` as some use lengths (`{1,10}`). If a random username with a length of 2 was generated, the chance of that username existing was very high. So I copied and hardcoded the regex for the site so that it generates the maximum length. See comments in code for more context.
cc: @DenavDot, you may find this interesting :)
3. Added regex to AllMyLinks
4. Use local `data.json` for unittests. This is more logical as we want to test the local code
5. Removed old code about `response_url` from tests
6. Fixed formatting of the code
> generate unclaimed username based on regex

- .github/workflows/update-site-list.yml
This action executes the site_list.py script when data.json is modified and the changes are pushed to the 'main' branch
The reason for adding this action is so that we do not have to rely on people creating PR to remember to run the script
> added GitHub Workflow to update site list

- README.md
Added `--nsfw` tag in `Usage` prompt with the description matching the `help` prompt of the parser's --nsfw flag
> Added `--nsfw` flag in documentation

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
Recently, @ThePornHelper raised an [issue](https://github.com/sherlock-project/sherlock/issues/1744) related to OnlyFans false negative. After going through the issue, I tried checking for some popular onlyfans creators on sherlock and as per the issue raised all of them were giving false negative.
So, I checked with the current method of checking the username availability. It the following API url:
`https://onlyfans.com/api2/v2/users/grandmasterchefjojo`
It returns a 400 error code and doesn't work at all.
Why it's happening? It requires a token be passed in the headers to for it to work.
After this, I tried using BurpSuite to find any other way to check availability and unfortunately there aren't any.
Even the wrong onlyfans.com/thisusernamedoesntexist777 URL also returns 200 in HTTP …
> Removed OnlyFans

- .gitignore
- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
- sites.md
All the false positives have been handled now. Some where removed and some were fixed
> Fixed false positives

- .replit
This replit file was added several years ago, back when replit allowed anybody to run code from a github repository, and it had poor support for auto-detecting projects. Now, replit can autodetect projects just fine, but replit only allows signed-up users run code, which makes this file significantly less useful and extraneous. I'm not sure why `run` is set to an empty string, that means that nothing will happen when a user clicks the `run` button.
This PR fixes that by removing the file, since it is extraneous and not useful.
> Remove `.replit` file

- removed_sites.md
- sherlock/resources/data.json
- sites.md
- Removed the "wykop.pl" duplicate in data.json and in sites.md
- Fixed wrong names in 3 latest removed_sites.md descriptions
> Remove wykop.pl duplicate and fix wrong names in removed_sites.md descriptions

- .github/workflows/pull_request.yml
Adds ruff to the pull request workflow.
Ruff was added to the tests job in the `main` workflow in https://github.com/sherlock-project/sherlock/pull/1759, but not to the `pull_request` workflow. Might be beneficial to keep them consistent to avoid any surprises when merging.
> Add ruff to pull request workflow

- sherlock/notify.py
- sherlock/result.py
- sherlock/sherlock.py
Discussions are taking place elsewhere about false positives and bot detection circumvention.
The Cloudflare bypass, **even if implemented**, will fail occasionally as Cloudflare updates their detection methods. Until the maintainer of whatever bypass mechanism is able to update _their_ tool, Sherlock users will randomly see false positives.
In either case, this PR significantly reduces the number of false positives that appear as more and more sites switch to using WAFs that function like Cloudflare. If a known WAF block page is detected, the QueryStatus of WAF is applied rather than running the standard (and now useless) error checks. Results with the status of WAF are only displayed with `--print-all` and bear a status message indicating such.
The error message also indicates that a …
> Reduce false positives (those caused by WAFs and bot detection)

- removed_sites.json
- removed_sites.md
- sherlock/resources/data.json
LinkedIn requires users to be signed in for normal visitation, but certain high-trust crawlers are allowed as well. Here, we masquerade as Googlebot to get past the 999 on valid usernames.
___
_site-list[.]py was skipped here as it'll probably run as an action on merge anyways_
> Add LinkedIn

- sherlock/resources/data.json
- sherlock/resources/data.schema.json
- sherlock/sites.py
- site_list.py
Nothing major here.
Sets the schema for data[.]json to allow for autocomplete, validation, etc. Reduces the likelihood of things being missed or left behind.
Setting the schema happened to uncover a couple minor instances of this (old username_unclaimed, noPeriod, etc). Those have been cleared.
_~~I may adapt this in the future to _disallow_ keys such as errorMsg when they don't match their dependent errorTypes, but that's a later problem.~~_ Done.
___
Looks like this was also mentioned back in #1336 and #1338. (so, closes #1336, closes #1338,  if merged)
> Set schema for manifest

- sherlock/resources/data.json
- sherlock/sites.py
Added catch for TypeErrors that may be caused due to the future addition of keys (if any ever get added), allowing Sherlock to continue past those errors. 
Removed $schema to accomodate older versions of the parser. This key will be added back in __after__ sherlock-project/sherlock#2088 (or other version incrementing change) is merged, giving users time to update.
___
@matheusfelipeog or @sdushantha : 
Merge is recommended as a hotfix.
PR addresses [comments made here](https://github.com/sherlock-project/sherlock/issues/1989#issuecomment-2099484854). Apparently the old way SitesInformation processed the data.json wasn't too friendly to the new key, so we're removing it for a now.
___
Fixes #2108
> Fix parser regression

- sherlock/sherlock.py
- sherlock/sites.py
Targets specified via --site will no longer be excluded when --nsfw is not set, even if flagged as nsfw. If the target was specifically listed by the user, it's probably because they want that target.
Fixes sherlock-project/sherlock#2103
> Skip content filter for explicitly chosen targets

- sherlock/resources/data.json
[ title, or see commit messages ]
Also closes #951 (adds linktree. linktree already added and is being fixed here.)
> Fix new false positives

- .gitignore
- Dockerfile
- README.md
- pyproject.toml
- setup.cfg
Closes #2036
Closes #2017
Related to #2111 (possible switch to poetry)
> Prepare PyProject for PyPi

- pyproject.toml
hotfix to https://github.com/sherlock-project/sherlock/pull/2116#issuecomment-2105992405
ref: #2116
> Build the package along with the data file for local use

- sherlock/sherlock.py
Hi,
just a simple try/except to handle an **OS Error** when using --tor flag. 
If you want to reproduce, please execute the code bellow: 
`python3 sherlock user_name --print-all --tor --json sherlock/resources/data.json`
This enhancement prints a message to the console and sherlock exit in a fashion way instead of an OS technical error message.
I hope this will great for te project.
Thanks all.
> Add exception handling for Tor option

- sherlock/resources/data.json
This PR aims to solve the false positive issue for the EyeEm website as mention in https://github.com/sherlock-project/sherlock/issues/2126
**Debugging the issue:**
I glanced through the code and the issue for EyeEm seems to be in the detection algorithm. The errorType is set to status_code, however a simple curl request to an unavailable username in EyeEm shows the response code as 200.
**Potential solution**
All unavailable usernames are accompanied by the error message:
"Whoops! We can't find the page you're looking for..."
If you wish I can make a PR for making this change and fixing it for this website. I understand that error message is the least reliable detection mechanism hence if you have better ideas I am all ears for it.
**Validating the fix**
Here is a screenshot verifying …
> Changed errorType to message for EyeEm

- sherlock/resources/data.json
EyeEm seems to have begun properly serving 404s again
This reverts commit 945a364970852a477f0796a5569627c12a7bb470.
> Update EyeEm test method

- sherlock/sherlock.py
Personally I'd rather want to see the version of Sherlock I am running and not the version of Python and `requests`. Thoughts?
**Before**
```
$ sherlock --version
sherlock 0.14.4
Python HTTP for Humans.:  2.32.3
Python:  3.12.3
```
**After**
```
$ sherlock --version            
Sherlock v0.14.4
```
> Removed uneeded info from --version output

- docs/INSTALL.md
- docs/README.md
Adds requirement.txt not required note, as discussed in #2156.
Adjusts install options in Readme, including the addition of Kali/Parrot/BlackArch.
> Update install docs

- .github/workflows/update-site-list.yml
- devel/site-list.py
With these changes, the site list will be written to the sherlock-project/sherlockproject.xyz repo where the docs and everything is located. This way, we wont have to manually update the list on the website.
> Update site list to sherlockproject.xyz/sites

- .github/workflows/update-site-list.yml
My fork does not delete all contents
> use a fork of the github action

- .gitignore
- docs/removed-sites.md
- sherlock/resources/data.json
- tests/test_probes.py
Pentestit was being used in the test to test sites using response URL. The checking on this site no longer works. It has therefore been removed and the Kofi is not being used instead in the tests
> Fixed tests due to broken sites

- docs/removed-sites.md
- sherlock/resources/data.json
- fixed freeCodeCamp false positive
- fixed LibraryThing false positive
- removed Zhihu due to false positives, closes #2153
> Fix false positives

- tox.ini
CentOS Stream seems to lack tox >= 4, so 3 is needed for proper support.
Version can be bumped safely once the CentOS package for tox is updated.
> Downgrade tox

- pyproject.toml
- sherlock/sherlock.py
Closes #2130 
Sample interaction without dependency:
```text
$ sherlock --tor test
Using Tor to make requests
Warning: some websites might refuse connecting over Tor, so note that using this option might increase connection errors.
[*] Checking username test on:
Important!
> Dependencies for --tor and --unique-tor are now optional, and WILL BE DEPRECATED in a future release of Sherlock.
> If you've installed Sherlock via pipx, you can install the dependency with `pipx install sherlock-project[tor]`.
> Other packages should refer to their packager maintainer's documentation, or install separately with `pipx install torrequest`.
[*] Search completed with 0 results
```
> Make torrequest optional

- sherlock/__init__.py
- sherlock/sherlock.py
> Except ImportError when not packaged

- sherlock/sherlock.py
Closes #2205 
Sample interaction:
```console
$ sherlock --site github ppfeister --dump-response
[*] Checking username ppfeister on:
+++++++++++++++++++++
TARGET NAME   : GitHub
USERNAME      : ppfeister
TARGET URL    : https://www.github.com/ppfeister
TEST METHOD   : status_code
Results...
RESPONSE CODE : 200
>>>>> BEGIN RESPONSE TEXT
<<<<< END RESPONSE TEXT
VERDICT       : Claimed
+++++++++++++++++++++
[+] GitHub: https://www.github.com/ppfeister
[*] Search completed with 1 results
```
Users experiencing F+ or F- can use the flag to more easily share site output and results, and contributors can use the flag to more easily debug targets.
> Add --dump-response flag

- sherlock_project/resources/data.json
ICQ.com returns false positive. There is no fix for it since the site was shut down on June 26, 2024
> remove ICQ.com

- sherlock_project/sherlock.py
Closes #2247, Closes #2249
I added a flag which disables creation of a txt file. However, you can still pass --csv or/and --xlsx flags to only create .csv or/and .xlsx file (without txt). This flag is False by default.
> A flag to disable creation of a txt file

- docs/removed-sites.md
I've notived, that https://codeforces.com is still included in the _removed-sites.md_ file, even though it has been added again some time ago here #1661.
> Remove Codeforces from removed-sites.md 

- Dockerfile
There's no need to wait and waste the time and bandwidth to wait for `apt-get update` for `pip3 install` ;)
> Remove not needed `apt-get update` in Dockerfile

- sherlock_project/resources/data.json
- **Add support for [Topcoder](https://topcoder.com/)**
- **Add support for [BoardGameGeek](https://boardgamegeek.com/)**
- **Add support for [Empretienda](http://empretienda.com.ar/)**
- **Add support for [Tiendanube](https://www.tiendanube.com/)**
Closes https://github.com/sherlock-project/sherlock/issues/2306, although I've just seen there is already a PR for that one 😅.
**Boardgamegeek** is a the leading community on boardgames.
**Empretienda** and **Tiendanube** are ecommerce platforms for small companies popular in Latam,
> Add BoardGameGeek and Small Ecommerce Platforms

- sherlock_project/resources/data.json
Librarything which uses errorType as message has error message as "Catalog your books online" but the error Message of Librarything has changed as "Error: This user doesn't exist".
So the above PR made the following changes to change the error message of the data.json of Librarything
> Change the errorMsg for Librarything

- sherlock_project/resources/data.json
> This PR addresses issue #2322 by adding support for detecting usernames on Velog.
1. I did `tox` testing by local after editing `data.json` file
2. and I ran `python -m sherlock_project qlgks1 nonewould_everuserthis7 --no-txt --site velog --local --print-all`
> Add support for velog

- sherlock_project/resources/data.json
Fixes #2317 
The Sherlock Project has always relied on [`nitter`](https://github.com/zedeus/nitter) for checking the availability of an username as it's impossible to use Twitter without JavaScript enabled & hence, can't be scraped easily.
Unfortunately **[nitter.net](https://nitter.net)** is down, which was being utilized for a long time & most of the alternate instances are behind a captcha or a browser integrity check page. Hence, I looked for an instance which can be accessed directly & updated the `urlProbe`.
List of instances can be found here - https://github.com/zedeus/nitter/wiki/Instances#public
> Fixed Twitter(X)

- sherlock_project/resources/data.json
With this PR, I add ``regexCheck`` value in ``data.json`` file that will check for valid username in the web pages  related to this issue https://github.com/sherlock-project/sherlock/issues/2313.
Its minimize the chance to return a result for a invalid username as the rules  for username from the pages is considered also
> Fix Invalid usernames for number of pages

- .github/ISSUE_TEMPLATE/bug-report.yml
Adds a **required** "Package version" input field to the issue templates. This field has been added only to the "bug report" issue template, as it is the only template where the package version information would be useful. If you believe it should be included in all issue templates or that the field should not be required, please let me know, and I will make the necessary changes.
Here is a screenshot of the updated template:
As always, please feel free to provide feedback or request any changes if necessary.
---
Closes #2353
> Add "Package version" field to issue templates

- sherlock_project/resources/data.json
This pull request addresses the issue where Sherlock consistently returns a false positive for `archive.org` due to the site being temporarily down and returning a `503` (Service Temporarily Unavailable) status code. The site also displays a specific message indicating the downtime.
**Changes:**
- Added an additional error message check for `archive.org` in `sherlock/sherlock_project/resources/data.json` to verify if the response contains the string "Other Internet Archive services are temporarily offline."
This change will help prevent false positives for `archive.org` by ensuring that Sherlock correctly identifies the downtime message and treats it as an invalid response.
Please review the changes and let me know if any further modifications are needed.
Fixes #2338
> fix: add additional error message check for archive.org downtime

- docs/README.md
Adds dnf for Fedora, and removes Parrot.
Also adds an admonition for all the ParrotOS bug reports that have been opening up. Agree/disagree on the warning?
> docs: update readme for fedora, parrot, 24.04

- sherlock_project/sherlock.py
Add type hints for exposed `sherlock` function, add `py.typed` to comply with PEP 561 and allow for detection by mypy for static type checking.
> Comply with PEP 561

- sherlock_project/resources/data.json
Before, the PyPi URL was always giving a false positive.
The new URL fixes that issue.
```sh
curl -o /dev/null -s -w "%{http_code}\n" https://pypi.org/user/real_pypi_username
200 
curl -o /dev/null -s -w "%{http_code}\n" https://pypi.org/user/fake_pypi_username
200
```
```sh
curl -o /dev/null -s -w "%{http_code}\n" https://pypi.org/_includes/administer-user-include/real_pypi_username
200
curl -o /dev/null -s -w "%{http_code}\n" https://pypi.org/_includes/administer-user-include/fake_pypi_username
404
```
#2313
> Fix PyPi URL

- sherlock_project/resources/data.json
This is one of the websites mentioned in #2374. After some experimentation, I discovered that Strava can now use a `status_code`.
Prior to my changes:
```sh
❯ ~/.local/bin/sherlock --local --site Strava blue this-username-doesnt-exist
[*] Checking username blue on:
[+] Strava: https://www.strava.com/athletes/blue
[*] Checking username this-username-doesnt-exist on:
[+] Strava: https://www.strava.com/athletes/this-username-doesnt-exist
[*] Search completed with 2 results
```
With my changes:
```sh
❯ ~/.local/bin/sherlock --local --site Strava blue this-username-doesnt-exist
[*] Checking username blue on:
[+] Strava: https://www.strava.com/athletes/blue
[*] Checking username this-username-doesnt-exist on:
[*] Search completed with 1 results
```
> Fix Strava false positives

- sherlock_project/resources/data.json
Tested via the following command:
```sh
❯ ~/.local/bin/sherlock adam account-that-doesnt-exist --local --site omg.lol --print-all
[*] Checking username adam on:
[+] omg.lol: https://adam.omg.lol
[*] Checking username account-that-doesnt-exist on:
[-] omg.lol: Not Found!
[*] Search completed with 1 results
```
API documentation is available at: https://api.omg.lol/#noauth-get-address-retrieve-address-availability
The `adam` account is owned by the owner of the service, so it should be safe as the claimed username.
I just discovered this project today. Let me know if I need to do anything else.
> Add support for omg.lol

- sherlock_project/resources/data.json
added support for the Digital Spy Forum. Digital Spy is a UK-based entertainment and media news website, known for covering television, movies, and celebrity news, as well as offering discussion forums for users.
> Adding DigitalSpy

- sherlock_project/resources/data.json
ASKfm was officially shutdown 1 December 2024 due to an announcement made by their administrators.
> Remove ask.fm + fix instagram  middleware

- .actor/Dockerfile
- .actor/README.md
- .actor/actor.json
- .actor/actor.sh
- .actor/dataset_schema.json
- .actor/input_schema.json
- docs/README.md
Dear Sherlock maintainers,
I have wrapped Sherlock as an Apify Actor by adding the [Actor definition](https://whitepaper.actor/#actor-definition-files?fpr=sherlock) in the `.actor` directory and published the [Sherlock Actor on Apify Store](https://apify.com/netmilk/sherlock?fpr=sherlock) a while ago. I've also added the [Actor status badge](https://docs.apify.com/platform/actors/publishing/status-badge?fpr=sherlock) and a brief usage description to the README, including the “Run on Apify” button that can drive further adoption.
**The Sherlock actor is used by ~200 unique users per month, with a total of around 800 users.** For the full description of the Actor, please see the [README](https://github.com/netmilk/sherlock/blob/main/.actor/README.md) file in the `.actor` directory.
Sherlock …
> Apify will sponsor your project: Sherlock Actor on Apify infrastructure

- sherlock_project/resources/data.json
PR adds support for detecting usernames on Tumblr.
Added Tumblr entry in sherlock/resources/data.json.
Detection uses status_code since Tumblr returns 200 for existing blogs and 404 for non-existing ones.
Closes #2505
> Add Tumblr Support to Sherlock

- sherlock_project/resources/data.json
This PR adds support for https://blitztactics.com to the project as requested in #2474.
NOTE: I am still a relative beginner with contributing to open-source projects, so I would appreciate feedback that anyone can provide.
Closes #2474
> Fix Issue #2474: Added support for Blitz Tactics

- sherlock_project/resources/data.json
Fixes #2458 
HTTP status code isn't working for Minecraft, so used `message` error type instead.
Sample response for claimed username:
```json
{
"id" : "bb83bdc4e8674dccb6568b49ad783596",
"name" : "Blue"
}
```
Sample response for unclaimed username:
```json
{
"path" : "/users/profiles/minecraft/blue475487563745",
"errorMessage" : "Couldn't find any profile with name blue475487563745"
}
```
> Fixed Minecraft

- docs/README.md
- docs/removed-sites.md
- sherlock_project/resources/data.json
In regards to issue #2492. This PR adds support for Pychess.
fixes #2494 
fixes #2492 
fixes #2532 
```fixes #2495 seems like another merged PR already solves this will unlink```
> Fix Issue #2492 and #2494 | Added support for Pychess | Remove TorrentGalaxy 

- sherlock_project/resources/data.json
> add: platzi.com

- .github/workflows/exclusions.yml
- .github/workflows/regression.yml
- pyproject.toml
- pytest.ini
- sherlock_project/sherlock.py
- tests/conftest.py
- tests/test_manifest.py
- tests/test_validate_targets.py
- tox.ini
I believe, several years ago, there was some functionality to fuzz usernames in search of F+s and some similar testing for F-s via `username_claimed`. This returns support for this functionality by way of `rstr`, using `regexCheck` as the base or a (simple) default pattern in its absence, along with single queries for F- with the claimed attribute.
Theoretically, this would be ran by a weekly action as well, allowing for automatic updating of an exclusions list for filtering of F+s without requiring manual intervention.
Any thoughts or objections?
Called via `pytest -m validate_targets` with support for parallelism via `pytest -m validate_targets -n 10` if `pytest-xdist` is installed (added to dev depends). Seems to work well so far.
Excluded from the default test suite (no reason to run …
> Return support for F+/F- detection via fuzzing

- sherlock_project/resources/data.json
namuwiki is ranked 5th in Top Websites Ranking in Korea by similarweb.
dcinside is ranked 7th, tistory is ranked 11th, soop is ranked 28th.
> feat: Add some popular website in Korea

- sherlock_project/resources/data.json
This PR remediates the false positive for Apple Discussions by updating the detection logic to look for "Looking for something in Apple Support Communities?".
> fix(sites): Remediate false positive for Apple Discussions

- sherlock_project/resources/data.json
Error Type has been changed to **_status_code_** from _message,_ as it was observed that 404 was returned for invalid usernames
> fix(sites):  Remediate False Positives for CyberDefenders

- sherlock_project/resources/data.json
Threads was showing false positives for non-existent users because the error message detection was incorrect.
Updated errorMsg:
- Old: "<title>Threads</title>" (generic, matches valid pages too)
- New: "<title>Threads • Log in</title>" (specific to non-existent users)
When a user doesn't exist, Threads redirects to a login page with the title "Threads • Log in". Valid user profiles have titles like "Username (@username) • Threads, Say more".
Tested with:
- Invalid user (impossibleuser12345): Correctly not found
- Valid user (zuck): Correctly found
This fixes the false positive issue where non-existent Threads profiles were being reported as found.
> fix(sites): Fix Threads false positive detection

- sherlock_project/sherlock.py
- sherlock_project/sites.py
So, I have fix a critical security vulnerability where HTTP requests could hang indefinitely, potentially causing denial of service.
Changes:
- Added 10-second timeout to version check API call
- Added 10-second timeout to GitHub pull request API call
- Added 30-second timeout to data file downloads (larger timeout for data)
- Added 10-second timeout to exclusions list download
Impact:
- Prevents infinite hangs that could freeze the application
- Improves user experience with predictable response times
- Fixes security issue flagged by Bandit static analysis (B113)
- Makes the application more robust in poor network conditions
> Security Fix: Add timeout parameters to HTTP requests

- sherlock_project/sherlock.py
Workflows where a txt file is still required should use --txt
> chore: make default --no-txt

- pyproject.toml
- sherlock/sherlock.py
Support for Tor has been removed. If users want to use Tor, it can be done using `--proxy`
**Edit:** (added by @ppfeister)
Closes #373 as moot
> removed support for tor

- .github/workflows/regression.yml
- Dockerfile
Adds automated testing for Docker image builds on merge/push to master and release branches.
- Added `docker-build-test` job to `.github/workflows/regression.yml`
- Extracts `VERSION_TAG` from `pyproject.toml` dynamically
- Builds Docker image with proper version tag
- Validates the built image runs correctly with `--version` flag
- Resolves Dockerfile syntax warnings
- ✅ Tested locally with `act` - all steps passed
- ✅ Docker builds successfully with VERSION_TAG=0.16.0
- ✅ Container runs and displays correct version
Closes #2196
> Add Docker build test to CI workflow (#2196)

- sherlock_project/resources/data.json
fixed , BoardGameGeek changed from /user/{} to /profile/{} URL structure. Also updated from message to status_code detection as the site no longer returns clear error messages for non-existent users.
> fix(sites): Update BoardGameGeek URL structure and detection method

- sherlock_project/resources/data.json
As the title suggests, it adds the support of WakaTime (Automated time tracking softwares for developers) to Sherlock.
This PR closes Issue #2319
> Add support for WakaTime

- .github/workflows/validate_modified_targets.yml
This pull request addresses an issue related to automatic target validation during chunking. Currently, the system performs a diff between the head and the base for chunking purposes. This approach causes incorrect target selection when the head is out of sync with the base.
The proposed fix changes the diff target to be the head against the latest upstream match (i.e., the default pull request diff) instead of the base. This correction ensures accurate target selection even when the head and base are not synchronized.
This behavior and the issue can be referenced in detail under issue #2568.
> fix(ci): Use merge-base for correct target validation

- sherlock_project/resources/data.json
This PR removes the duplicate Bluesky entry in data.json. While not a critical fix, it improves code cleanliness and resolves a linting error.
> Removed duplicate Bluesky entry in data.json

- sherlock_project/resources/data.json
This PR remediates the false positive for Blitz Tactics by updating the detection logic to look for "That page doesn't exist".
> fix(sites): Remediate false positive for Blitz Tactics

- sherlock_project/resources/data.json
**PR description:**
This PR adds AWS Skills Profile to Sherlock’s supported sites in data.json. 
An AWS Skills Profile is a personalized, verifiable online profile on [AWS Skill Builder](https://skillbuilder.aws/) that allows individuals to showcase their AWS learning journey and achievements, including verified AWS certifications, learning milestones, and digital badges.
The configuration uses a unique substring (`shareProfileAccepted":false`) for reliable detection of non-existent usernames, addressing the challenge of JavaScript-rendered error messages.
- Site details and detection logic follow Sherlock’s contributing guidelines and Code of Conduct.
- No changes to core logic; only a new site entry.
- Reviewed for schema compliance and duplicate key cleanup as noted.
> Add AWS Skills Profile site to Sherlock
