sherlock.py

Quick change. Realized the code looks messy when done in a hurry. :smile:

Refactor error printing code

---

data.json

social website used to keep track of anime and manga and make friends.

added myanimelist.net

---

README.md

Update README.MD with Python 3.6 requirement

Update README.MD with Python 3.6 requirement

---

sherlock.py

A small change to ensure the file is automatically closed.

Ensure raw file is automatically closed

---

sherlock.py

[isort](https://github.com/timothycrosley/isort/blob/develop/README.rst) cleans up the imports for readability.
```python
#! /usr/bin/env python3
import csv
import json
import os
import platform
import re
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from concurrent.futures import ThreadPoolExecutor
import requests
from requests_futures.sessions import FuturesSession
from torrequest import TorRequest
```

Run isort on the imports

---

data.json
sites.md

Added support for YouPic, House-Mixes.com, Letterboxd and Coderwall

Added YouPic, House-Mixes, Letterboxd and Coderwall

---

requirements.txt
sherlock.py

Fixed issue #5, using `Colorama`. Notice there is another PR using `Hue` here => #62 to resolve the same issue. I think both of them work well on Windows 10 with `PowerShell` and `Command Prompt`. I have tested both softwares but I have not tested on the Linux machine. Since `Colorama` is well known as cross OS and my PC crashed yesterday while installing Python 3.7 (Damn it!), I would not worry too much about it but if anyone would like to tested on their Linux distros and MacOS are welcome.

[Alternative] - Solve issue 5 with Colorama.

---

sherlock.py

Fix versioning

---

data.json
sherlock.py

~20 websites threw non-404 error codes

Changed error code from 404 to not 2XX

---

README.md

Add to docker hub

---

data.json

Fixed Dailymotion false positive. 
Issue here : #56

Fixed Dailymotion false positive

---

sherlock.py

This is just a suggestion, of course, there are still something need to be work on. For instance, duplicate code, etc. I reckon this PR could improve readability and make it much easier for people modify in the future.

Use Colorama syntax for better readability.

---

data.json
sites.md

Just found your project in the trending page, here you go for my contribution!

Add Mastodon to the site list

---

data.json
sites.md

All nicknames registered in Telegram can be found using [t.me](https://t.me/) website.

added Telegram (search by @nickname)

---

sherlock.py

Implemented feature mentioned in #115.

Made parameter for site name not case sensitive.

---

sherlock.py

In some countries with Internet censorship, some websites cannot be accessed directly. Using a proxy like Socks5 is a solution. Using the `all_proxy` environment variable can do this, but not elegantly.
This PR adds the full functionality of utilizing a proxy to make requests without introducing other dependencies. The code is linted with AutoPEP8, too.
BTW, this is a bloody useful tool!

Add proxy functionality

---

README.md
sherlock.py
tests/__init__.py
tests/all.py
tests/base.py

This is the next installment of #37.  It adds the basic testing infrastructure.
I did take some time and implement this with unittest.  This will give a better starting point than something home grown.
I expect that there is going to be many additions to the tests, but I wanted to get something actually merged into the main line now.  If I wait until everything is done, it may be quite a while.  And, this will give developers something to run.

Add Basic Testing Infrastructure

---

README.md

added @sdushantha as the original creator

---

README.md

Updated asciinema to reflect recent changes. If you don't mind, I will from now on update the asciinema every time a cosmetic changes will be made.

Updated asciinema

---

sherlock.py

With the new parameter --json (or -j) you can optionally pass a URL or a path where a valid json exists, and will parse it accordingly.

Added the ability to load external json files.

---

sherlock.py

Added an --folderoutput (-fo) which is used whenever multiple usernames are present and it places the username.txt files inside that folder.
Also created --output (-o) which is used whenever a single username is present and it places the contents of the results inside that file.

Optional output parameters

---

data.json
sherlock.py
tests/all.py

Another piece of #37. 
There were quite a few sites that worked fine by looking at the HTTP status (as opposed to depending on the exact error text).  So, I converted them to the more robust method.  And, I added them to the tests.

Add More Tests For Sites

---

.gitignore
data.json

Steam Group support is confirmed to be reliable as I implement it this way in my own [checker](https://github.com/checker/cli).
Also, I added the configuration directory for all of JetBrain's IDEs to the .gitignore

Added Steam Group support, Added .idea dir to .gitignore

---

data.json

Another iteration on #37.
Added more sites to JSON driven tests.
I have ran the tests often enough that AngelList is now refusing to answer.  It thinks that it is seeing suspicious activity from my IP address.  It is going to be hard to get reliable tests, but we need to have something.

More And More Tests

---

data.json

Another iteration on #37.
Added more sites to JSON driven tests.
66.9% coverage.

More And More And More Tests

---

data.json

Another iteration on #37.
Added more sites to JSON driven tests.  All tests pass on my PC, but there are still random failures when the tests run on Travis.
92.6% coverage.

More And More And More And More Tests

---

README.md

Just added a little graph which updates itself overtime. 📈

Added stargazers graph to README

---

README.md
data.json
sherlock.py

Just a feature I thought of while testing it out.
Not sure if it's just easier for me to pull your changes to my branch every update given the insignificant nature of the change, but nonetheless :)
Basically just adds a --nonotfound option to reduce output by remove the 'Not Found!' prints. I can rename it to make it nicer: --quieter, or --reduced, or something may be better. Easy tweak I'd be happy to make.

No not found

---

sherlock.py

Moves all the `print` log related functions into something more readable and reasonable.
Just cleaned up some code here. I aware there are modulation going on to this project? Hope this PR wouldn't effects to the modulation progress. I also realized some file have different coding style. I wonder would it be great to have a coding standard for people to contribute to this project? Code get messier every time a PR is made. Just a suggestion.

Org code for removing all the purpose print functions.

---

load_proxies.py

Another PR for cleaning up the code and make code consistent across the project. Make easier for everyone who is going to contribute to this project in the future. 
I reckon this style of documenting is a much standard way? Please ignore this PR if this style is approved in this project. Otherwise, I think this is a better docstring style.

Move docstring into function, and remove duplicate import.

---

README.md

Update preview image from `README.md` file.
Instead of a static image, just have a GIF file instead. Since the demo itself is really short, the total clip length is 30 seconds; I couldn't think of a reason to have people link to another website for just to see a demo. What do you guys think?
\
**Check out my branch to see how it look** => [jcs-pr/sherlock](https://github.com/jcs-PR/sherlock)

New preview in the README file.

---

site_list.py

Since other `.py` files use spaces, convert tabs to spaces in this file to avoid the use of mixed spaces and tabs in a file.
I was reading the file directly from GitHub and realized this file has use of mixed spaces and tabs at the same time. I presume if we have the style guide then we definitely need to specify the use of spaces or tabs in it.

Fixed mixed of tabs and spaces in a single file.

---

data.json

Added Myspace to checked usernames (404 error when username does not exist).
_Please note this is my first pull request, so feel free to let me know if I am doing this wrong._

Added Myspace to data.json

---

data.json

Adds support for the popular rhythm game "osu!".

Add support for osu!

---

data.json

Adds support for the BoingBoing comments system

Add support for BoingBoing

---

data.json

Adds support for Gfycat profiles

Add Gfycat Support

---

data.json

Adds support for the Pokemon Showdown game

Add support for Pokemon Showdown

---

data.json
sites.md

Adding support for OK and updating list of sites

Adding support for OK and updating list of sites

---

data.json
sites.md

Added support for codechef.

---

data.json

Adding virgool.io website to site-list

Add virgool.io

---

data.json

Add support for [LeetCode](https://leetcode.com/)
Best regards

Add LeetCode

---

data.json

Hi
This PR is for Issue #232
Reconfigured the code to check for usernames using Gitlab API. 
If the username doesn't exist the Gitlab API returns an empty array.
Thanks and Regards,
Sathish

ISSUSE-232 Gitlab check method

---

data.json

Solves problem metioned [here](https://github.com/sherlock-project/sherlock/pull/237#issuecomment-511182185)

Fix Virgool

---

.travis.yml

As suggested at https://github.com/sherlock-project/sherlock/issues/235#issuecomment-511245466  Results: https://travis-ci.com/cclauss/sherlock
https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing

Travis CI: Add SherlockSiteCoverageTests as a parallel run

---

data.json

Just added the site for Filmo.gs and verified tests.

Update data.json to add Filmo.gs

---

data.json

This is different from dot com version which is for blogs.

Add WordPress.org

---

data.json

Such a popular app and Sherlock didn't know about it. Surprising :P

Add TikTok

---

data.json

Brew is a beautiful podcast player for the listeners and a simple yet powerful tool for creators.
Built by the makers of BuyMeACoffee.com.
And BuyMeCoffee.com is a free, fast and beautiful way for creators to receive tips.

Add Brew & BuyMeACoffee

---

data.json

Add segmentfault.

---

data.json

Adding Tellonym.me

---

README.md
data.json
sherlock.py

Issue #314 reported a problem with Paypal and Duolingo.  I saw a problem on Paypal, but Duolingo is working for me.

Paypal Fix

---

data.json

Added support for [Teknik](https://teknik.io). Usernames used for testing:
- [red](https://user.teknik.io/red)
- [noonewouldeverusethis7](https://user.teknik.io/noonewouldeverusethis7)

Add Teknik

---

data.json

Add fanpop

---

data.json

Add Hubski

---

data.json

I've added Lobsters. Signups on the site are invite only to avoid spam and slow down registrations.
Regex Check:
https://github.com/lobsters/lobsters/blob/791b21f60a2e952cabe5187559c8fb7724b7b8aa/app/models/user.rb
(line 87)

Add lobste.rs

---

data.json

added Polygon, Wikidot, GuruShots, Shockwave, ImgUp.cz, Alík.cz and Sbazar.cz.
all websites were tested for claimed/unclaimed usernames.

added a few sites

---

README.md

Hello! I am a university student taking a technical writing course. For one project we need to make suggested edits to repos on github. 
Please use the following suggestions at your discretion :)
- reduced use of word 'you' to increase formality of writing
- removed empty words to make documentation more concise 
Thank you for your time!

University student documentation edits

---

README.md
data.json
sherlock.py

- Added a new site: https://www.7cups.com
- Fixed few typos and updated few comments to follow PEP-8 standards
Note: Few tests failing before the following commits

Added 7Cups site; Fixed typos 

---

data.json

Sites added:
- CNET
- CapFriendly
- Fiverr
- Jimdo
- HubPages
- LiveLeak
- Gamespot
- Cracked
- Viadeo

added 9 new sites

---

sherlock.py

Fixes "Illegal Username Format For This Site!" shown with the `--print-found` parameter 

---

data.json

added GPSies

---

Dockerfile
docker-compose.yml

- Remove unnecessary `apk update`
- Set image name in `docker-compose.yml`

Chore / Minor docker improvements

---

data.json

Added Sports Tracker

---

data.json

Sites added:
* Redsun.tf
* Kiwi Farms
* DRIVE2.RU
* GipsysTeam
* AudioJungle
Issues fixed:
fixes #418  
fixes #419 
fixes #420

added 5 new sites

---

data.json

I've added a new site: Facenama.com

add Facename

---

data.json

fixes #435 
fixes #436 
fixes #437 
fixes #438 
fixes #439 
fixes #440

added 7 new sites

---

data.json

Fix #447
Remove an extra space in data.json which causes a KeyError

Remove an extra space in data.json

---

sherlock.py

Made this in response to issue #358. Adds a `--no-color` option on the command line and a `color=True` keyword argument to the `sherlock`, `get_response`, and `print_*` functions. 
Sorry about my american spelling, I can change that if it's a problem. Great library!

Add --no-color option

---

data.json

Fixed username_claimed for labpentestit - capitalised CSV.

Fixed_LabPentestIt

---

data.json

Many sites have been added. Something that got me thinking was that most of these sites are forums. I am sure there are over 1000 forums on the web and a new one can be in a matter of seconds, so I am not really sure if we should be adding so many forums. But anyways, it does have a good side. The scope is larger ¯\\_(ツ)_/¯

added many more sites requested by @torerobo

---

data.json

Added support for [PokerStrategy](www.pokerstrategy.net), closes #509.

Added PokerStrategy support

---

data.json
removed_sites.md

The error message changed requiring `"errorMsg"` to be changed

Fixes furafinity

---

data.json

This will fix one of the false positives for usernames with a period (**.**) mentioned by @dd-pardal

added regexCheck for AskFM

---

data.json

This fixed the false positive for TrashboxRU

added regexCheck to TrashboxRU

---

data.json
data_bad_site.json
removed_sites.md

Removed InsaneJournal as it returns false positives when giving a it a
username with a period. I was not able to find what the criterias were
for a valid username on InsaneJournal, so the best thing to do is to
remove it
----
Dont mind the branch name. I accidentally committed to the old branch which was used to fix the the IFTTT false positive and dont know how to revert that.

removed InsaneJournal

---

data.json

Added support for [Booth.pm](https://booth.pm/), an online Japanese community shopping service.

Added booth.pm site

---

data.json

Adds the PCGamer forum and closes #532.

Added PCGamer forum

---

data.json
sites.md

changed dis.cool to tracr.co

---

data.json

Adding support form 6 websites.
**Related to** #502 
career.habr
euw
freelance.habr
realmeye
steamid
**Related to** #503 
kali community
**Related to** #520 
raid forums

Adding support form 6 websites

---

.travis.yml
README.md

Try to get the CI tests working.

Add change directory to CI so tests are executed in proper context.

---

.github/workflows/sherlock_test.yml

Set python version in github actions based on file change
Resolves #570 
Reference: https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

Set python version based on file change

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
README.md

Add new github action config files
Resolves #570  [Comment](https://github.com/sherlock-project/sherlock/issues/570#issuecomment-630580864)

Add separated GitHub actions

---

removed_sites.md
sherlock/resources/data.json

Creative Market was removed because it now has a captcha

removed Creative Market

---

removed_sites.md
sherlock/resources/data.json

removed pvpru because we are now getting an access denied error

removed pvpru

---

removed_sites.md
sherlock/resources/data.json

These sites return false positives when using a username which contains
a period. Since we could not find the criteria for the usernames for this site, it will be removed
because of this

removed easyen, pedsovet, and radioskot

---

sherlock/resources/data.json

Revert [merge request](https://github.com/sherlock-project/sherlock/commit/9e273a042f04fd1a9bd0f08b42460493266f3153), that returned sited removed earlier (redsun, pedsover, etc.)

Remove again sites removed earlier

---

Dockerfile
docker-compose.yml

Hey. I've added the missing Workingdir in the Dockerfile. Issue #643 
I have also removed the image from the compose-file since we are building the image locally

add WORKDIR in Dockerfile. Remove Image in compose

---

data_bad_site.json
removed_sites.md
sherlock/resources/data.json

removed Mixer, fixes #680

---

sherlock/resources/data.json

An online forum-like community targeted towards political changes.
- Alexa rank: 257,457
- Fluctuates in popularity during political events
Sources:
https://www.alexa.com/siteinfo/countable.us

Add countable.us

---

data_bad_site.json
removed_sites.md
sherlock/resources/data.json

The enpoint that was used to check for usernames no longer exists

removed KanoWorld

---

data_bad_site.json
removed_sites.md
sherlock/resources/data.json

Paypal is now checked using ErrorMsg instead of ResponseURL.

PayPal works now

---

sherlock/resources/data.json

Tinder Title Hack. No JS Processing needed.

No more False Positive on Tinder

---

sherlock/resources/data.json

No more False Positives on Wikipedia

---

sherlock/resources/data.json

Using API
https://api.polarsteps.com/users/byusername/{}

Fixed False Positives on Polarsteps

---

sherlock/resources/data.json
sites.md

Issue #413 
Used Redirected Title as ErrorMsg.

Added Support for Strava

---

sherlock/sherlock.py

@hoadlck 
> If the request fails, then there will be an uncaught exception. That does not seem right.
This PR should fix it

added error checking while checking for updates

---

sherlock/resources/data.json

Add [hackaday.io](https://hackaday.io/)

Add Hackaday

---

sherlock/sherlock.py

Adding line break at the end of the generated file

---

sherlock/resources/data.json

make it to english instead of russia

remove russia in www.chess.com

---

sherlock/resources/data.json

Add new site:
- https://tryhackme.com

Add TryHackMe

---

sherlock/resources/data.json
sherlock/tests/all.py

I think this fixes the tests failing.
Not exactly sure why the Error Message was causing it in the first place.

Facebook Change Error Type to Status Code

---

removed_sites.md

Removed comment on remove_sites.md about Basecamp

Removed comment on why basecamp was ever added

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

I have removed all the websites which return false results. These sites will of course have to be fixed in the future, especially Instagram as it is one of the most popular social media sites. 
I unfortunately do not have much time to fix these issues. So for now, I'm just removing them.
Closes #785
Closes #784
Closes #777
Closes #776
Closes #764
Closes #433

Removed all websites that have been reported for false positives/negatives

---

sherlock/resources/data.json

Reverts sherlock-project/sherlock#781

Revert "CashMe Fix"

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/reporting-false-negative.md
.github/ISSUE_TEMPLATE/reporting-false-positive.md
.github/ISSUE_TEMPLATE/site-support-request.md

These issue templates should hopefully get the issues organized and make it easier to help people out.

added issue templates

---

CONTRIBUTING.md

Fixed some small grammar mistakes in the contribution guide.

Fixed Grammar

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

**False positives that have been fixed:**
- EyeEm
- Repl.it
- Vero
- VirusTotal
- WattPad
- opennet (fixes #825)
- Facenama (fixes #826)
- Imgur
- Medium (fixes #824)
- Codepen
- ColourLovers
All of these false positive fixes were taken from #807, so all of the credit goes to @pkubiak who put their time and effort into finding a fix. The reason why I created this PR is because as discaused in #807, I wanted that PR to be split into 3 different PRs.  Since I had some free time today, I decided to quickly copy the false positive fixes that @pkubiak created in #807 and  make a seperate PR just for the false positive fixes.
Again, all credits go @pkubiak 👍

Fixed many of the false positives

---

sherlock/__main__.py

I have just removed the additional if-statement and merged the condition into a single if-statement.

Change if statement in __main__.py

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

Credits to @pkubiak for finding this

removed Filmogs because they shut down

---

sherlock/resources/data.json

Added [ICQ](https://icq.com/) to sites.

Added support for ICQ

---

sherlock/result.py
sherlock/sherlock.py
sherlock/sites.py

Seeing that majority of the comments were of the form `# Comment`, I have just changed all occurrences of `#Comment` to
`# Comment` to keep the comment style consistent.

Consistent comment style

---

README.md
sherlock/sherlock.py

Save csv file to output directory (if specified).

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

I currently do not have enough time to find a fix for the false positives. So those sites have been removed for now.

Remove false positives

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

removed Ebay due to too long of a response time

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

I have removed all the site reporting false positives. I have not taken a look at the issues or PRs in this repo so there might be more to fix. My fixes may be duplicates of other people's fixes in the pending PRs bu as of now, it is more time efficient if I go ahead and fix them myself. 
I did remove some major sites such as Twitter and YouTube, but that is hopefully temporary.

Cleaned up the evident false positives

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json
sites.md

Hello,
The issue with reddit seems to be that they now return 404 status only if you pass a cookie in headers and they always expect a language header and return the error message in the corresponding language.
This pr should fix the issue and make reddit working again.

Add reddit back in

---

sherlock/resources/data.json

venmo has changed their user links, they are venmo.com/u/{USER} now.

venmo users start with /u/ now

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json
sites.md

Thanks to @SethFalco Sherlock now supports POST requests and therefore we are able to bring back Fiverr :tada:

Added back Fiverr

---

sherlock/resources/data.json

Existing account:
``curl https://www.chess.com/callback/user/valid\?username\=blue``
```json
{"valid":false,"messages":["That username is taken. If this is you, \u003Ca href=https:\/\/www.chess.com\/login\u003Elog in\u003C\/a\u003E!"],"usernameSuggestions":[]}
```
---
Non existing account:
``curl https://www.chess.com/callback/user/valid\?username\=noonewouldeverusethis7``
```json
{"valid":true,"messages":["Username is valid"],"usernameSuggestions":[]}
```

Fix chess.com errorMsg

---

sherlock/__init__.py
sherlock/__main__.py
sherlock/notify.py
sherlock/sherlock.py
sherlock/sites.py

I made a few small changes to the output message to make it more friendly for the users.The difference is shown in the screenshots below

Small output changes

---

sherlock/resources/data.json

TradingView resource data has been fixed 

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

Added:
- Airbit
- Autofrage
- Bikemap
- Cryptomator Forum
- eBay.com
- eBay.de
- Envato Forum
- Fameswap
- Finanzfrage
- G2G
- Genius (Artists)
- Genius (Users)
- Gesundheitsfrage
- Ghost
- GitBook
- Grailed
- Gutefrage
- Ionic Forum
- Joplin Forum
- KEAKR
- Listed
- LottieFiles
- Mapify
- Motorradfrage
- Needrom
- OGUsers
- Rclone Forum
- Reisefrage
- Splice
- Sportlerfrage
- SWAPD
- ThemeForest
- TRAKTRAIN

Add 33 sites

---

sherlock/resources/data.json
sites.md

This Pull Request aims to add the website LessWrong to Sherlock.
LessWrong is a community for people interested in rationality.

Add LessWrong

---

sherlock/resources/data.json

Added https://www.codeforces.com/ using response_URL method

Added site: codeforces

---

sherlock/resources/data.json

added a new social media website "clubhouse"

Updated sites.json

---

sherlock/resources/data.json

Fixed a False-positive error for Site Smule - had to change errorType to message
Fixed errorMsg for Site Gumroad - Text in Browser slightly changed

Site adds and fixes

---

sherlock/resources/data.json

added bezuzyteczna

---

sherlock/__main__.py

1. Use the first part of sys.version to print Python version instead of converting and adding parts of sys.version_info
2. To check Python version, we can simply use a tuple comparison

Improve version checking code

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

removed Designsipiration, fixes #1305

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

I have currently just removed the sites that contain false positives. But I will fix things up and add them back during the summer holidays :+1: 
fixes #1315
fixes #1319
fixes #1318
fixes #1317
fixes #1314

Fix false positives

---

sherlock/tests/test_multiple_usernames.py

I created a unit test for the feature i made a few days ago for multiple usernames.

add unittest for multiple username

---

sherlock/notify.py
sherlock/tests/test_multiple_usernames.py

I have changed the notify.py in order to show: The number of results when the process is finished.

Add number of results in the end of the process

---

.gitignore
requirements.txt
sherlock/sherlock.py

Complete issue #1366
In this pull request i modified the following files:
1) requirments.txt i added pandas to requirments
2) Sherlock.py i added parses .xlsx and create a method to export the result as xlxs file if the user use the --xlsx parameter
3).gitignore add *.xlxs in order not to add result files into github

add xlsx file option by using --xlsx parameter 

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json
sherlock/tests/all.py

Removed Pinterest due to errors in tests

removed Pinterest

---

sherlock/resources/data.json

#1400 does the same but changes were made in the tests which resulted in conflicts in the PR. So I am making these changes myself to prevent us from waiting for the author of #1400 to make the changes. All credits goes to them

fixed Zhihu false positive

---

removed_sites.md
sherlock/resources/data.json

removed PCPartPicker

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

removed Ebay

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

dealing with a few false positives

Deal with false positives

---

sherlock/resources/data.json
sites.md

fix urlMain name for nnRu

---

sherlock/resources/data.json

Add OGUsers

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

Removed 2 sites giving false positives

False positive

---

sherlock/resources/data.json

Fixed the false positive with the Star Citizen/Robert Space Industries website so will now correctly display positives and no longer display false positives. Whonix also now correctly reports existing accounts as well, while not displaying false positives.

Fixed false positives

---

sherlock/resources/data.json

changed tinder URL to one that accurately gives results

Fixing Tinder false positive

---

sherlock/sherlock.py

This is in relation to #1360 
Having a set default timeout would help those unfamiliar with the code from getting stuck.

added default timeout of 60 seconds

---

CODE_OF_CONDUCT.md

Fixes #1486 
The Code of Conduct should be updated from version 1.4 to the most recent version 2.1 to ensure that the content is up-to-date and relevant, as things change in the community.

docs: update the code of conduct to the latest version

---

README.md
sherlock/sherlock.py

Updated the help message suite the new default timeout from #1483

version bump and made help suite the new default timeout

---

sherlock/resources/data.json

* added support for AO3
* have tested against claimed and unclaimed usernames

Added site: Archive of Our Own

---

sherlock/resources/data.json

Please consider for Hacktoberfest
#hacktoberfest #hacktoberfest-accepted

Added Harvard Scholar Site

---

sherlock/resources/data.json
sherlock/sherlock.py
sherlock/sites.py

Removed NSFW sites to be run by default.
Can still be included by adding the --nsfw or -n flag
As mentioned in #1475
Consider for #hacktoberfest2022
hacktoberfest hacktoberfest-accepted

Excluded NSFW sites by default.

---

sherlock/resources/data.json

Added new site.
https://sessionize.com/
Correct URL : https://sessionize.com/jason-mayes
Incorrect URL : https://sessionize.com/jason-mayesxyz
Network error 404.
#hacktoberfest #hacktoberfest2022

Added Sessionize to sites

---

sherlock/resources/data.json

Added slides com

---

sherlock/resources/data.json

This adds a search for users on https://ctan.org for contributors of TeX packages

Add CTAN as a site

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

removed Google Developer

---

README.md
sherlock/sherlock.py

Close #1284
Documentation for feature added by #1298

Added documentation for similar usernames checks

---

sherlock/resources/data.json

Add Yandex Music

---

removed_sites.md

added link re: raidforums

---

Dockerfile

Every RUN command will create a new layer, and every new layer increases the size of the final image.

One RUN layer less

---

sherlock/resources/data.json

Adding isNSFW field for xHamster

---

sherlock/resources/data.json

- Fixed The issue with False positive for KOOAPP
- Updated URL for searching

fixed issue with Kooapp for false positive #1493

---

sherlock/resources/data.json
sites.md

URL:
https://www.geeksforgeeks.org

Added GeeksforGeeks com

---

sherlock/resources/data.json

Added two Gaming forums support. 
1. NintendoLife
2. MMORPG Forum
Let me know if I need to change anything.

Added NintendoLife and MMORPG Forum

---

sherlock/notify.py
sherlock/sherlock.py

In response to:
https://github.com/sherlock-project/sherlock/issues/1639

Add --browse functionallity

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

Sherlock should not return any false positives now :+1:

Fixed all the false positives

---

README.md

For better understanding, I changed a few lines in the README.md file.

Changed a few sentences in Docker Notes.

---

removed_sites.json
sherlock/resources/data.json
sherlock/sites.py

I couldn't change [removed_sites.md](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md) because removing the variable was much more difficult with the text in-between.

Remove fixed value of "username_unclaimed" #1628

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

removed BinarySearch.io

---

sherlock/tests/base.py

We had removed the username_unclaimed from data.json but forgotten to remove it from the tests

fixed tests

---

sherlock/sherlock.py

apply --print-found when writing csv/xlsx files as well

---

.github/workflows/main.yml
.github/workflows/nightly.yml
.github/workflows/pull_request.yml
.github/workflows/update-site-list.yml

Test on valid Python versions: https://devguide.python.org/versions
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
* https://beta.ruff.rs
@sondreal Your review, please.

GitHub Actions: python-version: [3.7, 3.8, 3.9, "3.10", 3.11]

---

.github/workflows/main.yml

Replacing flake8 with ruff in main.yml

---

sherlock/resources/data.json

closes #1836

---

sherlock/resources/data.json

added a finnish social networking site, https://irc-galleria.net

added IRC-Galleria

---

sherlock/sherlock.py
sherlock/tests/test_multiple_usernames.py

changed two functions names to pep8 style, black formatter did its thing, another way to do interpolate_strings

black formatted, fixed interpolated_string, and some function naming

---

sherlock/sherlock.py

Fix the float type conversion in the timeout_check

---

README.md
sherlock/sherlock.py

Should use `{?}` instead of `{%}`.
---
resolve #1968
**refs**:
- #1823
- #1284
- #1298
- #1518

Fix the special string in docs to check for similar usernames

---

sherlock/resources/data.json

Adding HudsonRock so that we can check if the username exists in stealerlogs

added HudsonRock

---

sherlock/resources/data.json

Adds https://aniworld.to/, which is a german Anime streaming site.

Add AniWorld

---

sherlock/resources/data.json

Added Kick at /sherlock/resources/data.json

Added Kick

---

removed_sites.json
removed_sites.md
sherlock/resources/data.json

Add BugCrowd, SteamID

---

sherlock/sherlock.py

Fixes sherlock-project/sherlock#2102 (see linked issue for details)

Fix displayed hyperlinks

---

sherlock/sites.py
site_list.py

Catches error and continues if it doesn't exist.

Add default return val to pop

---

sherlock/sherlock.py

Bumping version due to #2106 and #2099

version bump 0.14.3 -> 0.14.4

---

devel/site-list.py

Fix incorrect path in update-site-list.py

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/false-negative.yml
.github/ISSUE_TEMPLATE/false-positive.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/site-request.yml

Revised templates applied to fork https://github.com/ppfeister/sherlock for testing and demo
Thoughts?

Revamp issue forms

---

sherlock/resources/data.json

fixed issue #2152 where CyberDefenders returns false positive

[2152-fix] fixed issue #2152

---

.github/workflows/regression.yml

Only execute GitHub action when needed

---

sherlock/resources/data.json

Mainly doing this to test if the new site list action works :)

Renamed Twitter to X

---

devel/site-list.py
sherlock/sherlock.py

Fixes hanging imports from #2151
Fixes bare f-string from #2178

Minor lint

---

sherlock/resources/data.json

LeetCode recently changed its user profile URLs from https://leetcode.com/username/ to https://leetcode.com/u/username/

New format for LeetCode profiles

---

.github/workflows/regression.yml

Add release branches to ci

---

sherlock/resources/data.json
sherlock/resources/data.schema.json

Return schema to manifest

---

devel/site-list.py

This should fix the failing action: https://github.com/sherlock-project/sherlock/actions/runs/10338869542/job/28617532582

updated sherlock path

---

sherlock_project/resources/data.json

add kaskus site

---

sherlock_project/resources/data.json

this is implementation for https://github.com/sherlock-project/sherlock/issues/2311

add VLR.gg support

---

sherlock_project/resources/data.json

Added Hugging Face to data.json 
@ppfeister

Add Hugging Face data.json

---

docs/README.md

This is to have the section listed in the GitHub index

Add star history section in README.md

---

sherlock_project/resources/data.json

This PR adds support for https://playstrategy.org/ to the project as requested in #2475.
NOTE: I am still a relative beginner with contributing to open-source projects, so I would appreciate feedback that anyone can provide.
Closes #2475

Fix Issue #2475: Added support for Playstrategy

---

sherlock_project/resources/data.json

Added Laracast website support which is educational website.
It works using status codes returning 200 if username exists and 404 if doesn't exist.

Added Laracast support

---

.github/workflows/validate_modified_targets.yml
sherlock_project/resources/data.json
tests/conftest.py

Automatically test modified targets upon PR

---

.github/workflows/validate_modified_targets.yml
devel/summarize_site_validation.py
pyproject.toml
sherlock_project/resources/data.json

Closes #2478 (PR also used to validate new validation workflow)

feat: add instapaper

---

sherlock_project/resources/data.json

fix(sites): Remediate false positive for AllMyLinks

---

sherlock_project/resources/data.json

This PR remediates the false positive for Mydramalist by updating the detection logic to look for "The requested page was not found".

fix(sites): Remediate false positive for Mydramalist

---

sherlock_project/resources/data.json

Detection algorithm has been changed to http_status from error message . This should ideally prevent any F+ or F- getting triggered

fix(sites):  Remediate False Positive for Roblox

---

sherlock_project/resources/data.json

Modified the Error Msg, which was outdated

fix(sites):  Remediate False Positive for SlideShare
